### ISSUE TITLE
Tracker 구현

### ISSUE THREAD

**Issue by woong-jae** [AL-GONG/Web#79]
채점 진행도를 추적하는 tracker 구현

- [x] 진행 상태를 내부적으로 관리한다. (IDLE, GRADING, DONE)
- [x] 전달받은 이벤트의 타입과 현재 상태에 따라 다음 상태로 전이한다.
- [x] 플랫폼, 문제번호, 코드, 메모리, 시간을 컨텍스트로 관리한다.
- [x] 이벤트 핸들러 리펙터링
